# 🚀 Spur GitHub Actions Workflow
name: Trigger Spur Webhook on Push 🔔

on:
    push:
        branches:
            -  main # 🌿 You can change this to your desired branch

jobs:
    trigger_webhook:
        runs-on: ubuntu-latest

        steps:
            - name: 📡 Curl Request to Trigger TestSuites on Spur
              run: |
                  curl -X POST \
                  -H "Content-Type: application/json" \
                  -H "repo: {{ GITHUB_REPOSITORY }}" \
                  -H "sha: {{ GITHUB_SHA }}" \
                  -H "SPUR_GITHUB_KEY: U2FsdGVkX19MejnFLTZjtmMVAwfPJIFnTCYkcq7X7VNarHR+BcIWN8q0ER/NfBzb" \
                  "https://spurserverwebappmulticore.azurewebsites.net/api/integrations/github/webhook?clientId=24&applicationId=25"

# 🎈 Happy testing with Spur!! 🎈
